name: Notificacion-dolar-diario

on:
  schedule:
    - cron: '0 18 * * *'  # 1:00 PM Lima (18:00 UTC)
  workflow_dispatch:       # Permite ejecuci√≥n manual

jobs:
  enviar_correo:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.1'
      - name: Verificar (RUTA)
        run: ls -la
      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ejecutar script de correo
        env:
          TOKEN_SUNAT_API: ${{ secrets.TOKEN_SUNAT_API }}
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          EMAIL_TO: ${{ secrets.EMAIL_TO }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_API_KEY: ${{ secrets.SUPABASE_API_KEY }}
        run: python -m app.services.infrastructure.test_gmail
