name: run_daily
on:
    schedule:
        - cron: '0 18 * * *'  # Runs every day at 1 PM LIMA (UTC)
    workflow_dispatch:        # allows manual trigger
jobs:
    hello_world:
        runs-on: ubuntu-20.04
        steps:
            - name: Clonar repositorio
              uses: actions/checkout@v4
            - name: Configurar Python
              uses: actions/setup-python@v5
              with:
               python-version: '3.11.1'
            - name: Instalar dependencias
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
                  - name: Ejecutar script de correo
            - name : Ejecutar script de correo
              env:
                EMAIL_USER: ${{ secrets.EMAIL_USER }}
                EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
                EMAIL_TO: ${{ secrets.EMAIL_TO }}
              run: |
                python -m app.services.infrastructure.test_gmail

            
